# Generated by Django 3.0.3 on 2020-12-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blank',
        ),
    ]
